-- Script to create database structure
CREATE DATABASE AgendaWeb;

GO USE AgendaWeb;

GO
CREATE TABLE USUARIO (
    ID UNIQUEIDENTIFIER NOT NULL,
    NOME NVARCHAR (150) NOT NULL,
    EMAIL NVARCHAR (150) NOT NULL UNIQUE,
    SENHA NVARCHAR (50) NOT NULL,
    DATAINCLUSAO DATETIME NOT NULL,
    PRIMARY KEY (ID)
);

GO
CREATE TABLE USUARIO (
    ID UNIQUEIDENTIFIER NOT NULL,
    NOME NVARCHAR (150) NOT NULL,
    EMAIL NVARCHAR (150) NOT NULL UNIQUE,
    SENHA NVARCHAR (50) NOT NULL,
    DATAINCLUSAO DATETIME NOT NULL,
    PRIMARY KEY (ID)
);

GO
