-- Script to create database structure
CREATE DATABASE AgendaWeb;

GO USE AgendaWeb;

GO
CREATE TABLE USUARIO (
    ID UNIQUEIDENTIFIER NOT NULL,
    NOME NVARCHAR (150) NOT NULL,
    EMAIL NVARCHAR (150) NOT NULL UNIQUE,
    SENHA NVARCHAR (50) NOT NULL,
    DATAINCLUSAO DATETIME NOT NULL,
    PRIMARY KEY (ID)
);

GO
CREATE TABLE EVENTO (
    ID UNIQUEIDENTIFIER NOT NULL,
    NOME NVARCHAR (150) NOT NULL,
    DATA DATE NOT NULL,
    HORA TIME NOT NULL,
    DESCRICAO NVARCHAR (500) NOT NULL,
    PRIORIDADE INTEGER NOT NULL,
    DATAINCLUSAO DATETIME NOT NULL,
    DATAALTERACAO DATETIME NOT NULL,
    ATIVO INTEGER NOT NULL DEFAULT (1),
    PRIMARY KEY (ID)
);

GO
